version: "3.8"

services:
  github-service-database:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_DB_USER
      - POSTGRES_PASSWORD=$POSTGRES_DB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB_DATABASE
    ports:
      - $POSTGRES_DB_HOST_PORT:$POSTGRES_DB_DOCKER_PORT
    volumes:
      - db:/var/lib/postgres
  github-service:
    depends_on:
      - github-service-database
    build: ./github-service
    restart: on-failure
    env_file: ./.env
    ports:
      - $APP_HOST_PORT:$APP_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://github-service-database:$POSTGRES_DB_DOCKER_PORT/$POSTGRES_DB_DATABASE",
        "spring.datasource.username" : "$POSTGRES_DB_USER",
        "spring.datasource.password" : "$POSTGRES_DB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "gitHubBaseUrl" : "$APP_GITHUB_BASE_URL"
      }'
    volumes:
      - .m2:/root/.m2

volumes:
  db: