spring:
  application:
    name: github-service
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5435/gh
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

gitHubBaseUrl: "https://api.github.com"
